### ISSUE TITLE
Category colors change automatically and randomly

### ISSUE THREAD

**Issue by watsonkelvin** [AmirHadifar/Flashcard#2]
I noticed that the category colors change randomly on orientation change. Is this intended? It would seem to make more sense if each Entity had a color attribute that stays fixed. I'm modifying the BaseEntity, but I'm an error:

``` java
public abstract class BaseEntity {

    @DatabaseField(id = true)
    public int id;

    @DatabaseField(dataType = DataType.STRING)
    public String title;

    @DatabaseField(dataType = DataType.STRING)
    public String subtitle;

    @DatabaseField(dataType = DataType.INTEGER)
    public int color;

    public abstract int getId();
    public abstract String getTitle();
    public abstract String getSubtitle();

    public int getColor(){
        return color;
    }
}
```

Exception:

``` bash
FATAL EXCEPTION: main
Process: com.march1905.dope, PID: 12092
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.march1905.dope/com.march1905.dope.ui.activity.MainActivity}: java.lang.RuntimeException: java.sql.SQLException: Unknown field 'color' from the Android sqlite cursor, not in:[id, subtitle, title]
    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2416)
    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476)
    at android.app.ActivityThread.-wrap11(ActivityThread.java)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344)
    at android.os.Handler.dispatchMessage(Handler.java:102)
    at android.os.Looper.loop(Looper.java:148)
    at android.app.ActivityThread.main(ActivityThread.java:5417)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
 Caused by: java.lang.RuntimeException: java.sql.SQLException: Unknown field 'color' from the Android sqlite cursor, not in:[id, subtitle, title]
    at com.j256.ormlite.dao.RuntimeExceptionDao.queryForAll(RuntimeExceptionDao.java:111)
    at com.march1905.dope.core.BundleDataBaseManager.getAllCategories(BundleDataBaseManager.java:102)
    at com.march1905.dope.ui.fragment.FragmentCategory.onViewCreated(FragmentCategory.java:64)
    at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1086)
    at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1252)
    at android.support.v4.app.BackStackRecord.run(BackStackRecord.java:742)
    at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1617)
    at android.support.v4.app.FragmentController.execPendingActions(FragmentController.java:339)
    at android.support.v4.app.FragmentActivity.onStart(FragmentActivity.java:602)
    at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1237)
    at android.app.Activity.performStart(Activity.java:6253)
    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2379)
    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476) 
    at android.app.ActivityThread.-wrap11(ActivityThread.java) 
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344) 
    at android.os.Handler.dispatchMessage(Handler.java:102) 
    at android.os.Looper.loop(Looper.java:148) 
    at android.app.ActivityThread.main(ActivityThread.java:5417) 
    at java.lang.reflect.Method.invoke(Native Method) 
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) 
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616) 
 Caused by: java.sql.SQLException: Unknown field 'color' from the Android sqlite cursor, not in:[id, subtitle, title]
    at com.j256.ormlite.android.AndroidDatabaseResults.findColumn(AndroidDatabaseResults.java:128)
    at com.j256.ormlite.field.FieldType.resultToJava(FieldType.java:815)
    at com.j256.ormlite.stmt.mapped.BaseMappedQuery.mapRow(BaseMappedQuery.java:60)
    at com.j256.ormlite.stmt.SelectIterator.getCurrent(SelectIterator.java:270)
    at com.j256.ormlite.stmt.SelectIterator.nextThrow(SelectIterator.java:161)
    at com.j256.ormlite.stmt.StatementExecutor.query(StatementExecutor.java:202)
    at com.j256.ormlite.stmt.StatementExecutor.queryForAll(StatementExecutor.java:118)
    at com.j256.ormlite.dao.BaseDaoImpl.queryForAll(BaseDaoImpl.java:241)
    at com.j256.ormlite.dao.RuntimeExceptionDao.queryForAll(RuntimeExceptionDao.java:108)
    at com.march1905.dope.core.BundleDataBaseManager.getAllCategories(BundleDataBaseManager.java:102) 
    at com.march1905.dope.ui.fragment.FragmentCategory.onViewCreated(FragmentCategory.java:64) 
    at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1086) 
    at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1252) 
    at android.support.v4.app.BackStackRecord.run(BackStackRecord.java:742) 
    at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1617) 
    at android.support.v4.app.FragmentController.execPendingActions(FragmentController.java:339) 
    at android.support.v4.app.FragmentActivity.onStart(FragmentActivity.java:602) 
    at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1237) 
    at android.app.Activity.performStart(Activity.java:6253) 
    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2379) 
    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476) 
    at android.app.ActivityThread.-wrap11(ActivityThread.java) 
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344) 
    at android.os.Handler.dispatchMessage(Handler.java:102) 
    at android.os.Looper.loop(Looper.java:148) 
    at android.app.ActivityThread.main(ActivityThread.java:5417) 
    at java.lang.reflect.Method.invoke(Native Method) 
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) 
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616) 
```

Where can I find the SQLite database structure?

**EDIT: I've submitted a [pull request](https://github.com/AmirHadifar/Flashcard/pull/3) addressing this issue.**

**Comment by hadifar** [comment]
Thanks , I when rotate screen fragment reCreated so drawable color change. I'll work on it.

**Comment by watsonkelvin** [comment]
Please check out the code in my pull request. I was able to move the logic of setting the color to the model instead. I tested this using my code and the colors persist across orientation changes.

**Comment by hadifar** [comment]
Thanks @watsokel I solve it in another way. Instead of adding attribute to Model I change ColorGenerator a bit. it produce specific color for each String.
